### ISSUE TITLE
v2.1.0 文章页面代码显示缺少

### ISSUE THREAD

**Issue by guomaimang** [mirai-mamori/Sakurairo#197]
![Capture](https://user-images.githubusercontent.com/47519540/118937091-bc88d000-b97f-11eb-81b1-c0a647998e40.PNG)

新版本2.1.0中,对markdown语法中代码的现显示不全，缺少字符，如上图所示
https://www.hanjiaming.com.cn/archives/2556

**Comment by KotoriK** [comment]
这是部分CSS样式缺失所致
下个版本会进行修复，你可以暂时引入下述样式解决（参考https://github.com/wcoder/highlightjs-line-numbers.js/#usage）：
```css
/* for block of numbers */
.hljs-ln-numbers {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;

    text-align: center;
    color: #ccc;
    border-right: 1px solid #CCC;
    vertical-align: top;
    padding-right: 5px;

    /* your custom style here */
}

/* for block of code */
.hljs-ln-code {
    padding-left: 10px;
}

```
