### ISSUE TITLE
白猫特效文字特效出错

### ISSUE THREAD

**Issue by CLanNT** [mirai-mamori/Sakurairo#652]
从CSS文件看白猫特效文字的故障特效应为红色蓝色闪烁（如Sakura模板中这样：https://2heng.xin
但实际使用中只能显示一半的特效，hover:before部分的特效无法显示。
查看了使用该模板的其它博客，特效文字都有此类问题。
（使用Edge和Chrome打开都不能正常显示，应该不是浏览器问题（吧））

**Comment by zhy201810576** [comment]
我的解决办法是修改主题目录下的**style.css**，大概在[4546](https://github.com/mirai-mamori/Sakurairo/blob/f3083d91240dded03ee387e8d4166178cd35d316/style.css#L4546)行位置，将`h1::before`选择器最后两个属性注释掉
```css
h1::before {
  display: block;
  content: " ";
  height: 80px;
  /*margin-top: -80px;*/
  /*visibility: hidden;*/
}
```
