### ISSUE TITLE
白猫样式LOGO二级文字垂直定位过小，导致二级文字与LOGO主体部分填充相重叠。

### ISSUE THREAD

**Issue by kanodaisuki** [mirai-mamori/Sakurairo#671]
**问题出处：**

白猫样式LOGO二级文字垂直定位过小，导致二级文字与LOGO主体部分填充相重叠。

**实际行为描述：**

元素重叠

**预期的行为：**

预期效果如下图：
![](https://image.kanochan.net/2023/03/16/20230316162349.png)

**复现步骤：**

Sakurairo默认配置下即可复现。

**配置与环境：**

- 问题页面：无
- PHP 版本：略
- 数据库类型 / 版本：略
- WordPress 版本：略
- 主题版本： Theme Version 2.5.10 Internal Version 18.0.0
- 使用的插件：无
- 浏览器：chrome 111.0.5563.65

**截图（若有）**
![](https://image.kanochan.net/2023/03/16/20230316161841.png)

**补充信息：**

fix：

```css
.logolink ruby rt {
    font-size: 10px;
    letter-spacing:2px;
    transform: translateY(-10px);
    opacity: 0;
    transiton-property: opacity;
    transition-duration: 0.5s, 0.5s;
}
```
